[
   {
      "circuit":"2_04",
      "description":"Voordeur PIR",
      "dev":"input",
      "handle_local":"no",
      "device_delay":30,
      "device_normal":"no",
      "unipi_value":0,
      "unipi_prev_value":0,
      "unipi_prev_value_timstamp":0,
      "state_topic": "unipi/bgg/voordeur/motion"
   },
   {
      "circuit":"3_01",
      "description":"Dakraam Contact",
      "dev":"input",
      "handle_local":"no",
      "device_normal":"nc",
      "unipi_value":1,
      "unipi_prev_value":1,
      "unipi_prev_value_timstamp":0,
      "state_topic": "unipi/bbg/bijkeuken/dakraam/contact"
   },
   {
      "circuit":"2_04",
      "description":"Bijkeuken LUX",
      "dev":"ai",
      "handle_local":"no",
      "device_normal":"no",
      "unipi_value":0,
      "unipi_prev_value":[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29 ],
      "unipi_avg_cntr":0,
      "unipi_prev_value_timstamp":0,
      "state_topic": "unipi/bgg/bijkeuken/lux"
   },
   {
      "circuit":"28D1EFA708000052",
      "description":"Temperatuur Sensor buiten",
      "dev":"temp",
      "state_topic":"unipi/buiten/voordeur/temperatuur"
   }
]
